name: Deploy to Railway

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Railway
        uses: railwayapp/railway-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_API_TOKEN }}
